### ISSUE TITLE
Query with where filter on null date fails

### ISSUE THREAD

**Issue by pastcompute** [strongloop/loopback-datasource-juggler#1328] opened 2017-04-17 05:32 UTC
# Description/Steps to reproduce

1. Using the loopback explorer
2. With a model that has a property with type Date
3. Attempt to query to return results where the Date has value null (note - using postgres as connector)
4. Explorer - filter set to `{"where":{"somedate":null}}`
5. Curl command - `curl -X GET --header 'Accept: application/json' 'http://localhost:3000/api/MyThings?filter=%7B%22where%22%3A%7B%22somedate%22%3Anull%7D%7D'
6. Note that opposite case works as expected, using `{"where":{"somedate":{"neq":null}}}`
7. See also #1320

# Expected result

* Return a set of objects where the Date type was null in the database

# Actual result

```
TypeError: Cannot read property 'hasOwnProperty' of null
    at /home/demo/loopback-play/node_modules/loopback-datasource-juggler/lib/geo.js:28:30
    at Array.forEach (native)
    at nearSearch (/home/demo/loopback-play/node_modules/loopback-datasource-juggler/lib/geo.js:21:25)
    at Object.nearFilter (/home/demo/loopback-play/node_modules/loopback-datasource-juggler/lib/geo.js:44:3)
    at Function.find (/home/demo/loopback-play/node_modules/loopback-datasource-juggler/lib/dao.js:1892:27)
    at SharedMethod.invoke (/home/demo/loopback-play/node_modules/strong-remoting/lib/shared-method.js:262:25)
    at HttpContext.invoke (/home/demo/loopback-play/node_modules/strong-remoting/lib/http-context.js:295:12)
    at phaseInvoke (/home/demo/loopback-play/node_modules/strong-remoting/lib/remote-objects.js:647:9)
    at runHandler (/home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:135:5)
    at iterate (/home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)
    at runHandlers (/home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:144:13)
    at iterate (/home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)
    at /home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25
    at /home/demo/loopback-play/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at execStack (/home/demo/loopback-play/node_modules/strong-remoting/lib/remote-objects.js:492:7)
```

# Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 7.4.0
$ npm ls --prod --depth 0 | grep loopback
loopback-play@1.0.0 /home/demo/loopback-play
├── loopback@3.5.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-postgresql@2.7.0
├── loopback-datasource-juggler@3.4.1
├── loopback-ds-readonly-mixin@1.0.1

```

**Comment by AnttiVikman** [comment] 2017-04-24 08:18
We are also seeing this issue with
* loopback-datasource-juggler@3.5.0
but it seems to work with
* loopback-datasource-juggler@3.3.0
* loopback-datasource-juggler@3.2.0

**Comment by ssh24** [comment] 2017-04-24 23:32
Closing this. Related to issue: https://github.com/strongloop/loopback-datasource-juggler/issues/1332

**Comment by ssh24** [comment] 2017-04-25 14:32
Reopening this issue to track https://github.com/strongloop/loopback-datasource-juggler/pull/1349

**Comment by ssh24** [comment] 2017-04-25 17:07
Thank you @pastcompute for adding the additional test cases. Closing this issue as the PR has been landed.

**Closed by ssh24** 2017-04-25 17:07 UTC
Labels: apex, in-progress

**Comment by tsexton6689** [comment] 2017-06-14 17:29
I am having this issue for an id on a relationship in a MYSQL DB, I have accounts that have a belongsTo relationship to Users (the ID is an INT(10) with the field checkout_user and I'm trying to find all the accounts that don't have users and the error i keep getting is: 

```
{
  "error": {
    "statusCode": 500,
    "name": "TypeError",
    "message": "Cannot read property 'hasOwnProperty' of null",
    "stack": "TypeError: Cannot read property 'hasOwnProperty' of null\n    at /app/node_modules/loopback-datasource-juggler/lib/geo.js:28:30\n    at Array.forEach (native)\n    at nearSearch (/app/node_modules/loopback-datasource-juggler/lib/geo.js:21:25)\n    at /app/node_modules/loopback-datasource-juggler/lib/geo.js:24:21\n    at Array.forEach (native)\n    at /app/node_modules/loopback-datasource-juggler/lib/geo.js:23:27\n    at Array.forEach (native)\n    at nearSearch (/app/node_modules/loopback-datasource-juggler/lib/geo.js:21:25)\n    at Object.nearFilter (/app/node_modules/loopback-datasource-juggler/lib/geo.js:44:3)\n    at Function.find (/app/node_modules/loopback-datasource-juggler/lib/dao.js:1891:27)\n    at SharedMethod.invoke (/app/node_modules/strong-remoting/lib/shared-method.js:270:25)\n    at HttpContext.invoke (/app/node_modules/strong-remoting/lib/http-context.js:297:12)\n    at phaseInvoke (/app/node_modules/strong-remoting/lib/remote-objects.js:649:9)\n    at runHandler (/app/node_modules/strong-remoting/node_modules/loopback-phase/lib/phase.js:135:5)\n    at iterate (/app/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/app/node_modules/strong-remoting/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)"
  }
}
```

Here is the filter i am using 
`?filter={"where": {"and": [{"checkout_user": null},{"scope_testing":"Commercial"}]}}`

I thought I would attach it to this bug because it seems to fit the same thing as mine. 

Here are my versions from package.json:

```
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mysql": "^2.4.0", 
```

**Comment by ssh24** [comment] 2017-06-14 19:49
@tsexton6689 There has been a recent fix on null value handling on the mysql connector. Do you mind giving it a shot by git cloning the [mysql repo](https://github.com/strongloop/loopback-connector-mysql) and npm linking it to your app and see if that fixes your issue?

If you are still having difficulties, please create a issue on the [mysql repo](https://github.com/strongloop/loopback-connector-mysql) with a good breakdown of the reproduction steps and we will look into it.

**Comment by tsexton6689** [comment] 2017-06-16 02:21
@ssh24 I npm linked it and the issue is still happening, i'll make an issue on the the mysql repo. Thanks.
