### ISSUE TITLE
EmbedsMany ID's with MongoDB set to String instead of ObjectID

### ISSUE THREAD

**Issue by sebastianhaas** [strongloop/loopback-datasource-juggler#750] opened 2015-11-03 14:44 UTC
When posting embedded models to a MongoDB datasource, the embedded instances ID's appear to be of type `String` instead of `ObjectId` like in any other case where we're dealing with IDs.

Please take a look at my test case at https://github.com/sebastianhaas/embeds-many-string-id.

STR:
- `npm install`
- `node .`

This will create an instance of the model `Book` and an embedded instance of `Chapter` in that book. The actual JSON in the database will be something like

```
{
    "_id" : ObjectId("5638c3466baf4c1e60accdd0"),
    "title" : "A first book",
    "chapterList" : [ 
        {
            "title" : "Chapter One",
            "pages" : 65,
            "id" : "9650ecce677750439cea5df1" <--- String
        }
    ]
}
```

where the chapter's ID is not an `ObjectId` but a `String`.

Please note that while this is a minimal example I already tried different options on the relation and a few other suggestions from the forums, SO and github issues.
These, amongst others, include:
- Any possible combination of `persistent: true`, `forceId: true`, `validate: true` as relation options
- Manually specifying a ID property of type `String` or `ObjectId` with any possible combination of 
  `"id": {
    "type": "string",
    "required": true,
    "generated": true,
    "id": true,
    "defaultFn": "uuid"
  },`

**Comment by Amir-61** [comment] 2016-05-17 00:59
Yes thats seems a bug to me; the validation is not implemented for `updateAll`/ `update`

**Comment by Amir-61** [comment] 2016-05-17 01:04
Would you like to contribute a patch and fix this issue?

**Comment by sebastianhaas** [comment] 2016-05-24 06:16
Do you confirm this as a bug? I can see if I can contribute a patch then.

**Comment by Amir-61** [comment] 2016-05-24 16:16
@sebastianhaas 

I just doubled check [your app](https://github.com/sebastianhaas/embeds-many-string-id) and on my second thought it may not be a bug and it can be an expected behaviour; IIRC for embeds relation the child's data is stored in the parent model and not in a separate child model so thats why we are getting the embedded instances ID's as type String instead of ObjectId like in any other case because the ID may not be from DB (although the id `9650ecce677750439cea5df1` seems to be from MongoDB ). I may be wrong; so I guess @superkhau is the one who may be more familiare with this. @superkhau could you please let us know more about this and whether it is considered to be a bug or not? Also could you please confirm that my understanding of `embedded` is right that the child data is not saved in a separate model and instead they are saved in parents model.

Thanks!

**Comment by Amir-61** [comment] 2016-05-24 16:33
@raymondfeng Could toy please take a look and let us know if this is a bug? Also your explanation can clarify lots of things...

Thanks

**Comment by jannyHou** [comment] 2016-08-05 21:05
@sebastianhaas @Amir-61 Since you attach `Chapter` to transient datasource, according to idType definition in transient connector: 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/connectors/transient.js#L30
, the default idType is `String`, i think that's why you get a string type.

But what confuses me is, you set `idInject` as `false` and don't define an id property for model `Chapter`, then which function defines the id property for you?

**Comment by sebastianhaas** [comment] 2016-08-17 13:54
@jannyHou I don't know where the ID property is coming from and I also don't know whether it is created by MongoDB or loopback.
It's just that MongoDB natively supports embedded models with ids so I don't see any reason why the return type would be a plain string?

**Comment by jjhesk** [comment] 2016-10-29 17:21
I have the same issue once i upgrade to the latest version of the juggler. I have issued a [ticket](https://github.com/strongloop/loopback/issues/2907) and it seems this thread is the source of the cause. Now what is the fix for having query the objectid from the rest api?

**Comment by sebastianhaas** [comment] 2016-10-29 19:03
I still think this is an issue. It's a shame that this is open for almost a year now, and its not even clarified if this weird and flawed behavior is expected for whatever reason. I still would be more than willing to help on this @Amir-61 @jannyHou @raymondfeng

**Comment by jjhesk** [comment] 2016-10-30 02:26
nope, this issue actually resurfaced recently and I am still able to find out the cause of it. I updated the recently versions of one of the component. If there is a fix, how or where do I turn on to accept string as in uuid format via http rest from the input and able to query the key as string in the db. This wasnt as issue like a month ago until I did `npm update`. =( It is very disappointing. do i need to consider a switch to using other framework...

**Comment by jannyHou** [comment] 2016-11-04 15:54
@sebastianhaas @jjhesk Let's clarify what's going wrong in mongdb:

From the sandbox provided by @sebastianhaas , if I understand correctly, you expect to see `ObjectId()` in chapter instance but get `string`.
  - The reason is you are using **transient** connector
  - If you use mongodb as connector chapter will have an `Objected()` type id in mongo database

For @jjhesk I believe your bug is a different problem, I understand that they both related to mongo id type, but remote query is a different story against calling function in code. If you think it's still a **VALID**bug , then please don't close it, I reopened it and will take a look later. And we will fix it if we can reproduce and confirm.

**Comment by sebastianhaas** [comment] 2016-11-04 16:34
Thanks for your clarification. But is it even possible to define an embedded relation using any other connector but `transient` and still have the embedded data inside the parent mongodb object?

**Comment by jannyHou** [comment] 2016-11-04 19:48
While @sebastianhaas I just tried to attach embedded model to mongodb, the embedded instances stored in mongodb database have `ObjectId` type id, but when you return the parent instance, the embedded children are still using `string` type id. 
And you are right, embedded models are supposed to attach to transient only.

There is a config property called `defaultIdType` you can use to specify the id type like
```
  "transient": {
    "name": "transient",
    "connector": "transient",
    "defaultIdType": "Number"
  }
```
but now we don't support `ObjectId` in loopback :(

**Comment by sebastianhaas** [comment] 2016-11-29 13:03
I think this can be closed if everyone agrees that this is expected behavior. It might be good to add some documentation though to explain where ids in embedded models come from and why they're different from models attached to a persistent data source directly.

**Comment by jannyHou** [comment] 2016-11-29 21:13
@sebastianhaas make sense. I created a pr to add it in doc: https://github.com/strongloop/loopback.io/pull/183

**Closed** 2016-11-30 15:59 UTC
Labels: connectors-nosql, doc, juggler-relations, team-apex
