### ISSUE TITLE
I can't query with like operator and '%' in value

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback-datasource-juggler#313] opened 2014-09-29 10:45 UTC
In the request filer:
```JSON
{"include":"categories", "where":{"title": {"like": "%Computer%"}}, "limit":20}
```

In mongodb debug :
```html
{ include: 'categories',
  where: { title: { like: '%Computer%' } },
  limit: 20,
  offset: 0,
  skip: 0,
  order: [ 'id' ] }
```

If i used the symbol "%" in the filter it can not find anything
but when i remove the symbol "%" it showed datas. i think, maybe it have problems with the query.

**Comment by raymondfeng** [comment] 2015-02-05 22:15
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/385

**Closed by raymondfeng** 2015-02-05 22:15 UTC

**Comment by Rima1992** [comment] 2020-01-09 14:50
if the text contains 'computer' this is the code
`"where":{"title":  {"regexp": "/Computer/"}}`
Otherwise, try this code 
`"where":{"title":  {"like": "Computer"}}` OR `"where":{"title":  "Computer"}`
