### ISSUE TITLE
Server crashes when trying to include related model through polymorphic relationship

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-datasource-juggler#589] opened 2015-05-13 11:56 UTC
Lets say I have the following 3 models:

     Person -> Membership -> Event.

A Person can have many Memberships, and a Membership can have many Events. Events can also be associated with other things, so they have Polymorphic relationship defined.

When looking up Events, I an include the relevant related Memberships through thje Polymorphic relationship, with a REST query filter like:

```json
{
  "where": {
    "referenceType": "Membership",
    "name": "created"
  },
  "include" : {
    "relation": "reference"
    }
  },
 "limit" : 10
}
```

If I also want to include the Person information that is related to the Membership, I should be able to do this according to the documentation:

```json
{
  "where": {
    "referenceType": "Membership",
    "name": "created"
  },
  "include" : {
    "relation": "reference",
    "scope": {
      "include": {
        "relation": "person"
      }
    }
  },
 "limit" : 10
}
```

However, this actually crashes the server completely, with:

> /devenv/build/node_modules/loopback-datasource-juggler/lib/include.js:217
            relation.modelTo.include(subItems, subInclude, callback);
                            ^
TypeError: Cannot read property 'include' of null
    at /devenv/build/node_modules/loopback-datasource-juggler/lib/include.js:217:29
    at /devenv/build/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1418:11
    at /devenv/build/node_modules/loopback-datasource-juggler/lib/dao.js:1358:5
    at allCb (/devenv/build/node_modules/loopback-datasource-juggler/lib/dao.js:1297:7)
    at /devenv/build/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:371:7
    at /devenv/build/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/devenv/build/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)

Firstly, it shouldn't be possible to crash the server with a REST query! Secondly, why I am getting this error? It is possible to include related models from related polymorphic relationships like I'm trying to do?

This is the Polymorphic relationship definition on the Event model:

```json
    "reference": {
      "type": "belongsTo",
      "polymorphic": {
        "foreignKey": "referenceId",
        "discriminator": "referenceType",
      }
    }
```
These are the relationships on the Membership model:

```json
    "person": {
      "type": "belongsTo",
      "model": "Person",
      "foreignKey": "personId"
    },
    "events": {
      "type": "hasMany",
      "model": "Event",
      "polymorphic": {
        "as": "events",
        "foreignKey": "referenceId",
        "discriminator": "referenceType"
      },
      "description": "Returns a list of events associated with a membership."
    }
```

And this relationship is on the Person model:

```json
    "memberships": {
      "type": "hasMany",
      "model": "Membership",
      "foreignKey": "personId",
      "description": "Returns a list of memberships associated with a person."
    },
```

**Comment by seriousben** [comment] 2015-05-13 12:13
I had the same problem not too long ago. Ended up being a wrong model name in my relation... which should probably not crash either but is caused by a developer error not a bad request.

**Comment by mrfelton** [comment] 2015-05-13 13:59
@seriousben - so you have been able to include relationships from related polymorphic entities of a base model like this?

I'm pretty sure there are no incorrect names in my model relations. The relations all work correctly when used directly.

I can't find any test case proving that this type of join works.

**Comment by mrfelton** [comment] 2015-05-13 16:40
See here where I have created some test cases that highlight the issue - https://github.com/strongloop/loopback/pull/1388/files

The first 2 tests work fine. The 3rd one in which I try to pull in an additional relationship from the related polymorphic model causes a fatal server crash.

**Comment by jjhiew** [comment] 2015-05-14 21:57
I've got a very similar issue, except it's not crashing the server.  Rather it is just not returning the correct response.  This happens with V.2.27.0, but not with 2.26.4.

`CoffeeShop -> Reviewer -> Contact (polymorphic)

***
CoffeeShop.findOne({
   include: {
     relation: "reviewer",
     scope: {
          include: {
             relation: "contact"
         }
     }
  }, where: {id: ID}
});
***

Prior to the latest update, everything work work correctly.  After today's update (2.27.0), it no longer return the Contact related model.

**Comment by doublemarked** [comment] 2015-05-22 16:12
I encountered this very same error today. None of my relations are named incorrectly. Feels like a bug in how `Inclusion` works.

**Comment by doublemarked** [comment] 2015-05-24 20:05
Hey - actually I updated modules today and no longer have this problem. Try updating to the latest `loopback-datasource-juggler`.

**Comment by jjhiew** [comment] 2015-06-11 21:42
As of 2.29.x, the issue with the missing nested related modules still hasn't been resolved.  I'm still on 2.26.4 because of this...  =(

**Comment by loay** [comment] 2016-01-14 21:38
Hi @mrfelton 
Is this issue still persisting?
Thanks.

**Comment by loay** [comment] 2016-01-15 19:46
Many Polymorphic relationship issues have been fixed in the recent version. If the issue is still persisting, please leave a comment and I will look into the issue. Thanks.

**Closed by loay** 2016-01-15 19:46 UTC
Labels: triage, waiting
