### ISSUE TITLE
DateType throws Error on invalid date

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback-datasource-juggler#1020] opened 2016-07-25 14:29 UTC
If getting an invalid date from mysql for example, DateType function in model-builder.js throws an error: "Error: Invalid date: Invalid Date" which is not easy to handle.
why not just return null instead and call it a day?

**Comment by azatoth** [comment] 2016-07-26 19:07
https://github.com/strongloop/loopback-connector-mysql/pull/179 could be a solution to the cause of this error; still exists though is the question regarding the thrown of exception.

**Comment by hussainak** [comment] 2016-10-23 13:45
This happens when date in my db is 0000-00-00 00:00:00

**Comment by superkhau** [comment] 2016-10-26 06:28
Can you provide a sample for us to reproduce the issue? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by hussainak** [comment] 2016-10-26 15:48
Yeah the only think you need to do is, setup a model with date type
property and go into the fb and set the date manually as given above. And
when you try to access that date it will throw the invalid date error.
Hope it helps.

**Comment by jannyHou** [comment] 2016-11-08 19:31
@azatoth @hussainak do you still run into this issue? If I understand correctly it only happens when you talk to mysql with native SQL query, in loopback you could not even create instance with invalid date.

And please provide us a sandbox as Simon said in https://github.com/strongloop/loopback-datasource-juggler/issues/1020#issuecomment-256260530 if you think it a bug. Thanks.

**Comment by superkhau** [comment] 2016-11-08 20:38
@jannyHou We can probably try to reproduce this based on https://github.com/strongloop/loopback-datasource-juggler/issues/1020#issuecomment-256391168

@azatoth @hussainak We would appreciate it if one of you could provide a link to a sample repo so @jannyHou can try to reproduce it by simplying cloning.

**Comment by dhmlau** [comment] 2017-04-21 20:30
@azatoth, I believe we've fixed it in PR https://github.com/strongloop/loopback-datasource-juggler/pull/1339.  Please verify.  If you're with the fix, we can close this issue.  Thanks.

**Comment by dhmlau** [comment] 2017-05-01 21:26
Closing this, since we believe it's been fixed in PR #1339.  If you still encounter this problem, feel free to reopen.  Thanks.

**Closed by dhmlau** 2017-05-01 21:26 UTC
Labels: apex, triaging
