### ISSUE TITLE
Invalid date: [object object] on include

### ISSUE THREAD

**Issue by hiddestokvis** [strongloop/loopback-datasource-juggler#717] opened 2015-09-10 09:28 UTC
Using the mongodb connector I get an "Invalid date: [object object]" error when I include a model that has a datefield but does not exits.

For example: I have a "Question" model and an "Answer" model. The "Answer" model has a datefield. When I look for Question.find({include:"answer"}) and there is an unanswered question I get this error.

The problem seems to be in the DateType function which gets an "Object" not a date as argument. I imagine a quick fix would be:

``` javascript
function DateType(arg) {
  if(typeof arg !== "object")
  {
    var d = new Date(arg);
    if (isNaN(d.getTime())) {
      throw new Error('Invalid date: ' + arg);
    }
    return d;
  }
}
```

**Comment by superkhau** [comment] 2015-09-11 17:22
Would you like to submit a patch?

**Comment by loay** [comment] 2016-05-31 19:46
Taking the discussion within the PR. Closing the issue. Thanks.

**Comment by bajtos** [comment] 2016-12-08 12:34
@loay we should not close issues until they are fixed. I.e. land the pull request first, back-port it if needed, and only then close the issue.

#724 was not finished, I am reopening this issue.

@hiddestokvis could you please provide us with a sample app reproducing the issue? I am not sure if the description will be enough.

**Comment by hiddestokvis** [comment] 2016-12-08 12:38
@bajtos I kind of fixed this for myself in #724. It's been a while but I can probably take the time to rebase and add tests for my solution and resubmit a merge request.

**Comment by bajtos** [comment] 2016-12-08 12:47
@hiddestokvis 
>  I kind of fixed this for myself in #724. It's been a while but I can probably take the time to rebase and add tests for my solution and resubmit a merge request.

That would be awesome!

**Comment by dhmlau** [comment] 2017-04-21 20:34
@hiddestokvis, I believe we have fixed it in this PR https://github.com/strongloop/loopback-datasource-juggler/pull/1339.
Could you please verify?  If you're good with this, we can close this issue.  Thanks.

**Comment by dhmlau** [comment] 2017-04-28 18:49
Closing this as we believe the problem is fixed.  If you still encounter this issue, feel free to reopen.  Thanks.

**Closed by dhmlau** 2017-04-28 18:49 UTC
Labels: apex, triaging
