### ISSUE TITLE
filter with related model's properties 

### ISSUE THREAD

**Issue by FelipeAguayo** [strongloop/loopback-datasource-juggler#730] opened 2015-10-06 21:34 UTC
I have the following situation:

Model:
```json
{
  "name":"Model",
  "plural":"Models",
  "idInjection":true,
  "properties":{
     "name":"string"
  },
  "relations":{
    "relOtherModel":{
      "type": "belongsTo",
      "model": "OtherModel",
      "foreignKey": "idOtherModel"
    }
  }
}
```
values Model: 
```js
[ {id:1, idOtherModel:1, name:'one'}
, {id:2, idOtherModel:1, name:'two'}
, {id:3, idOtherModel:2, name:'three'}
, {id:4, idOtherModel:3, name:'four'}]
```
OtherModel:
```json
{
  "name":"OtherModel",
  "plural":"OtherModels",
  "idInjection":true,
  "properties":{
     "name":"string",
     "state":"string"
  }
}
```
values OtherModel:
```js
[ {id:1, name:'otherOne', state: 'created'}
, {id:2, name:'otherTwo', state: 'deleted'}
, {id:3, name:'otherThree', state: 'created'}]
```

I want to get the values of "Model 1" that belong to "OtherModel" with state "created".

Example: 
* [ GET ] http://localhost:3000/api/Models?filter={"where":{"relOtherModel.state":"created"}}
* Model.find({where:{"relOtherModel.state":"created"}}, function(err, models){});
* Other Solution.

Result values:
```js
[ {id:1, idOtherModel:1, name:'one'}
, {id:2, idOtherModel:1, name:'two'}
, {id:4, idOtherModel:3, name:'four'}]
```
Any solution? :(

PD: the query must be from Model.

**Comment by jlvdh** [comment] 2015-10-08 10:00
Seems related to: https://github.com/strongloop/loopback/issues/517

**Comment by superkhau** [comment] 2015-10-14 06:33
@FelipeAguayo Can you verify if your issue is related to strongloop/loopback#517?

**Comment by FelipeAguayo** [comment] 2015-10-14 14:29
yes, but i'm working with the mysql connector.

**Comment by superkhau** [comment] 2015-10-14 21:57
Thanks. I will mark this issue as a duplicate.

**Comment by bajtos** [comment] 2016-06-02 11:54
I think this is not exactly a duplicate of  strongloop/loopback#517, let's keep it open.

**Comment by bajtos** [comment] 2016-06-02 11:55
Actually let's use https://github.com/strongloop/loopback/issues/683 to keep track of this feature request.

**Closed by bajtos** 2016-06-02 11:55 UTC
Labels: feature, major

**Comment by pookdeveloper** [comment] 2018-12-02 18:09
This is not resolved yet ? Thanks

**Comment by bajtos** [comment] 2018-12-03 13:09
> This is not resolved yet ? 

No, see https://github.com/strongloop/loopback/issues/683
