### ISSUE TITLE
DataAccessObject.upsert/updateOrCreate - no hooks triggered

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#159] opened 2014-07-01 14:01 UTC
Contrary to create(), upsert() does not call any before/after hooks at all.

In addition, it appears to be impossible for any of the beforeHooks to cancel the pending action (save for example). `next(new Error('Halted'))` apparently doesn't work.

**Comment by bajtos** [comment] 2015-02-03 12:30
I am closing this issue, we are moving away from `beforeUpdate/afterUpdate` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `before save` and/or `after save` hooks and open a new GH issue if you run into any problem.

**Closed by bajtos** 2015-02-03 12:30 UTC
Labels: #tob, bug

**Comment by jmls** [comment] 2015-02-15 18:17
does this mean that we have to write our own upsert hooks to find the model id we have a string ID ?

I am trying to PUT (upsert) data over existing records , but am getting an error back 

code":11000,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index

which suggests that the record is being created rather than updated

**Comment by bajtos** [comment] 2015-02-17 15:29
> does this mean that we have to write our own upsert hooks to find the model id we have a string ID ?
@jmls Definitely not. AFAIK, LoopBack automatically converts (coerces) the model id to the correct type. What database are you using? I remember there were some issues with ID coercion in the MongoDB connector.

**Comment by jmls** [comment] 2015-02-17 15:30
I am using mongo ...

On 17 February 2015 at 15:29, Miroslav Bajtoš <notifications@github.com>
wrote:

> does this mean that we have to write our own upsert hooks to find the
> model id we have a string ID ?
> @jmls <https://github.com/jmls> Definitely not. AFAIK, LoopBack
> automatically converts (coerces) the model id to the correct type. What
> database are you using? I remember there were some issues with ID coercion
> in the MongoDB connector.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-datasource-juggler/issues/159#issuecomment-74685822>
> .
>



-- 
Julian Lyndon-Smith
IT Director,
dot.r
http://www.dotr.com

**Comment by bajtos** [comment] 2015-02-17 16:53
> I am using mongo ...

@jmls could you please open a new issue in [loopback-connector-mongodb](https://github.com/strongloop/loopback-connector-mongodb/issues/new) and provide steps how to reproduce the problem?
