### ISSUE TITLE
Problem with ValidationAsync

### ISSUE THREAD

**Issue by FelipeAguayo** [strongloop/loopback-datasource-juggler#667] opened 2015-07-20 15:09 UTC
every time I do a validation with 'ValidationAsync' I get the following response:

```json
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The 'Model' instance is not valid. Details: (unknown).",
    "statusCode": 422,
    "details": {
      "context": "Model",
      "codes": {},
      "messages": {}
    },
    "stack": "ValidationError: The 'Model' instance is not valid. Details: (unknown).\n    at EmbedsMany.create (node_modules\\loopback-datasource-juggler\\lib\\relation-definition.js:2682:39)\n    at ModelConstructor.method (node_modules\\loopback-datasource-juggler\\lib\\relation-definition.js:726:33)\n    at ModelConstructor.fn_create [as __create__models] (node_modules\\loopback-datasource-juggler\\lib\\scope.js:282:7)\n    at SharedMethod.invoke (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\shared-method.js:234:25)\n    at HttpContext.invoke (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\http-context.js:375:12)\n    at node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:608:11\n    at execStack (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:448:7)\n    at RemoteObjects.execHooks (node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:452:10)\n    at node_modules\\loopback\\node_modules\\strong-remoting\\lib\\remote-objects.js:605:10\n    at node_modules\\loopback\\lib\\application.js:357:13"
  }
}

and the model instance is VALID!! u.u

**Comment by bajtos** [comment] 2015-10-22 11:00
Hi @FelipeAguayo, is this issue still relevant? Could you please create a sample app reproducing the problem per [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)?

**Comment by FelipeAguayo** [comment] 2015-10-22 14:22
@bajtos: Ok, i will try to reproduce the problem.

**Comment by FelipeAguayo** [comment] 2015-10-22 16:54
code: https://github.com/FelipeAguayo/loopback-sandbox.git

In this case, when the validationAsync (common/models/model.js) is 'invalid' onError not work.

**Comment by superkhau** [comment] 2015-11-09 20:11
@FelipeAguayo I haven't been able to look at this yet, but would you like to submit a patch?

**Comment by superkhau** [comment] 2015-11-30 22:45
@FelipeAguayo I don't get any errors when I clone and run your project. Can you provide some step-by-step instructions on how to reproduce the issue?

**Comment by superkhau** [comment] 2015-11-30 22:46
@bajtos Taking out of TOB since its not fully triaged yet. Adding major label to make sure we keep an eye on this.

**Comment by superkhau** [comment] 2015-12-14 01:22
@FelipeAguayo Ping.

>@FelipeAguayo I don't get any errors when I clone and run your project. Can you provide some step-by-step instructions on how to reproduce the issue?

**Comment by FelipeAguayo** [comment] 2015-12-14 14:16
@superkhau Pong. It's been a long time since this matter was created, it is no longer a problem for me.

**Comment by superkhau** [comment] 2015-12-14 20:50
@FelipeAguayo TY, closing.

**Closed by superkhau** 2015-12-14 20:50 UTC
Labels: major, triage
