### ISSUE TITLE
Switching to from loopback-datasource-juggler@2.53.0 to  loopback-datasource-juggler@2.55.2 breaks microgateway

### ISSUE THREAD

**Issue by jgeddes2001** [strongloop/loopback-datasource-juggler#1467] opened 2017-08-18 02:25 UTC
# Description/Steps to reproduce

1. clone the repo
`git clone -b 1.6.x git@github.com:strongloop/microgateway.git`

2. install and test
`npm i`
`npm test`

3. install and test switching
`rm -rf node_modules`
`git checkout npm-shrinkwrap.json`
change npm-shrinkwrap.json to loopback-datasource-juggler@2.55.2
`npm i`
`npm test`

4. tests fail

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment] 2017-08-21 14:53
@jgeddes2001  could you please point us 1) which test case failure that you think it's related to juggler? 2) the corresponding error logs?  

cc @b-admike

**Comment by jgeddes2001** [comment] 2017-08-21 15:30
Basically the microgateway-datastore fails to initialize with new juggler... So, all the testcases fail now..

Here are some logs i collected with DEBUG=* using old (good) and new (bad) versions of the juggler..

[bad.log.txt](https://github.com/strongloop/loopback-datasource-juggler/files/1239264/bad.log.txt)
[good.log.txt](https://github.com/strongloop/loopback-datasource-juggler/files/1239265/good.log.txt)

**Comment by jannyHou** [comment] 2017-08-21 17:05
I followed the steps in https://github.com/strongloop/loopback-datasource-juggler/issues/1467#issue-251122464 with node@4.7 and npm@3.10.10, all test pass.

According to @jgeddes2001 they are testing with node@8, sounds like the failure happen with some node versions.

**Comment by jannyHou** [comment] 2017-08-21 17:58
hi @jgeddes2001 after I switch to node8 I see these failure, are they the same ones you observe?
```
1) invokePolicy compress-data:
     Error: expected body 'z-method: POST\nz-host: localhost:8889\nz-url: //invoke/testCompression\nz-auth: undefined\nz-content-length: undefined\nz-content-type: undefined\nz-content-encoding: gzip\nz-transfer-encoding: chunked\nz-user-agent: APIConnect/5.0 (MicroGateway)\nraw: H4sIAAAAAAAAE/NIzcnJVwjPL8pJAQBWsRdKCwAAAA==body: Hello World' to match /raw: H4sIAAAAAAAAA\/NIzcnJVwjPL8pJAQBWsRdKCwAAAA==/
      at error (node_modules/supertest/lib/test.js:265:13)
      at Test._assertBody (node_modules/supertest/lib/test.js:188:18)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:691:12)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at node_modules/async-listener/glue.js:188:31
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:198:9)

  2) oauth2 token API token endpoint - password auth url (HTTPS) ok:
     Error: expected 200 "OK", got 403 "Forbidden"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at node_modules/async-listener/glue.js:188:31
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:198:9)

  3) oauth2 token API token endpoint - password auth url (https without tls profile) ok:
     Error: expected 200 "OK", got 403 "Forbidden"
      at Test._assertStatus (node_modules/supertest/lib/test.js:232:12)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/supertest/node_modules/superagent/lib/node/index.js:703:3)
      at IncomingMessage.<anonymous> (node_modules/supertest/node_modules/superagent/lib/node/index.js:922:12)
      at endReadableNT (_stream_readable.js:1045:12)
      at node_modules/async-listener/glue.js:188:31
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:198:9)
```

**Comment by jgeddes2001** [comment] 2017-08-21 19:42
Sadly, no... I'm seeing all the testcases fail (doesn't even complete) when I switch to new juggler.. I think I only see the three failures when I use the old juggler..

I'm trying to recreate your success(with npm@3.10.10 node@4.7.3), but having what must be environment issues as I've been running pretty much solely in npm@5.0.3 node@8.1.1 for a while now..

**Comment by jannyHou** [comment] 2017-08-21 20:25
True..@jgeddes2001 I looked into the report too: https://cis-jenkins.swg-devops.com/job/nb/job/microgateway%7Emaster/label=x64%20&&%20linux%20&&%20nvm%20&&%20dbs,nodeVersion=8/5/console

And on my end, I get same result (3 failures) with juggler@2.53.0, 2.53.1, 2.54.0, 2.55.0, 2.55.2,
Do I have to run `git checkout npm-shrinkwrap.json` **everytime** I switch to a new juggler version?
When I test them, I only run that command once after I first cloned the repo.

**Comment by jgeddes2001** [comment] 2017-08-22 04:56
@jannyHou I found that npm-shrinkwrap.json gets a bunch of stuff in there every `npm i` .. I `git checkout npm-shrinkwrap.json` and `rm -rf node_modules` then `npm i` each time to get accurate results..

**Comment by jgeddes2001** [comment] 2017-08-22 05:13
Was able to test with similar environment to @jannyHou 
```
jeremys-mac:microgateway jgeddes$ npm -v
3.10.10
jeremys-mac:microgateway jgeddes$ node -v
v4.7.3
```

Seeing same results as I saw with node8.. few failures with juggler@2.53.0... testcases don't even complete at juggler@2.55.2..

**Comment by dhmlau** [comment] 2017-08-22 14:25
Looks like in 5080, we're not supporting Node v8 yet.  
I assume tests passed in microgateway with juggler@2.53.0 (previously used version).  I wonder what had changed to have those 3 tests failed this time given the failure also happened in node v4.

cc @smartmouse

**Comment by jgeddes2001** [comment] 2017-08-22 17:23
I'd nevermind node8 currently... with node4.7.. **few failures with juggler@2.53.0... testcases don't even complete at juggler@2.55.2..**

**Comment by kjdelisle** [comment] 2017-08-23 15:01
@jgeddes2001 Can you show us the errors from test runs that demonstrate the regression?

**Comment by jgeddes2001** [comment] 2017-08-23 15:15
@kjdelisle Good and bad log in above comment is probably what you want.. It's not during regression testcases, it's just a simple bring up..

**Comment by jannyHou** [comment] 2017-08-23 15:38
@jgeddes2001 We are glad to help solve the problem, while we don't know is it a regression or is it juggler that causes the failure.

Microgateway as a downstream dependency passes all PRs between 2.53.0 and 2.55.2.
And as we all see, if 2.53.0 also fails with node4,7, it's hard for us to continue the investigation without a good juggler version that makes all tests pass...

**Comment by dhmlau** [comment] 2017-08-23 17:18
@jgeddes2001, in the bad log, which line number is showing test failure?  I searched for `loopback` in the file and the matches I could find are related to `strong-globalize`, which I don't believe is the cause of the errors.  Since the test cases are in your module, it would be helpful if you could provide us where in the juggler is causing the failure, in order for us to continue to help.  

Also, how did you get the good log?  From the above conversations, it seems like even @2.53.0 has failure too.

**Comment by jgeddes2001** [comment] 2017-08-24 20:49
@jannyHou as I stated above... at node4.7 all the testcases fail if I move to juggler@2.55.2... if I stay at 2.53.0 they work (with a few failures)... @dhmlau I don't see where you guys are logging the failure in the logs either.. but you are failing.. essentially, it appears the loopback app doesn't serve up the apis if I switch to 2.55.2... 

when you run our testcases in microgateway:
success (node4.7 juggler@2.53.0):
```
 653 passing (4m)
  7 pending
```
failure: (node4.7 juggler@2.55.2) (ends before getting through all testcases because the app doesn't work and we fail out)
```
    71) should expect ratelimit rejection
npm ERR! Test failed.  See above for more details.
```

**Comment by kjdelisle** [comment] 2017-08-28 16:44
@jgeddes2001 Let's be clear about something; I'd like a stack trace demonstrating that the problem is related to a change made to juggler before my team invests a significant amount of time debugging microgateway.

The last time this happened, the reason was that the microgateway-datastore was using **non-standard** definitions for its models, which were broken as a result of an API/doc-compliant fix made in loopback-datasource-juggler@2.x.

Pointing towards a series of test failures in a given time window is not sufficient reproduction to fix an issue, let alone determine who will be responsible for said fix.

**Comment by jgeddes2001** [comment] 2017-08-28 18:03
@kjdelisle I would argue that wasn't a bug on our side either. That's a regression caused by a change you made, not us.  I'm guessing this issue is similar.

**Comment by jgeddes2001** [comment] 2017-08-28 18:22
I'd also add, I really don't want to chase this... it works as is.. doesn't with new version..  I'm being asked to up the version of the juggler... @smartmouse why do we need to up the version?

**Comment by kjdelisle** [comment] 2017-08-28 18:41
>@kjdelisle I would argue that wasn't a bug on our side either. That's a regression caused by a change you made, not us. I'm guessing this issue is similar.

@jgeddes2001 I'm asking you to **prove that**; the burden of proof is on the consumer to provide evidence that there is a problem.

As for why you want to upgrade to a newer version of the juggler, it comes with many other bug fixes that are worthwhile.

**Comment by jgeddes2001** [comment] 2017-08-28 19:10
@kjdelisle to me.. https://github.com/strongloop/loopback-datasource-juggler/issues/1467#issuecomment-324753403 is proof.. 

simple as.. old juggler = works.. new juggler fails..

**Comment by jgeddes2001** [comment] 2017-08-28 21:14
This is related to @smartmouse 's request to update the juggler... Spoke with mgmt..  We currently have the shrinkwrap hardcoded to the old version, no plans to upgrade the microgateway to anything newer (we'll just stay on the old/working version).   I guess you can close until you force us to update versions.

**Comment by smartmouse** [comment] 2017-08-29 01:14
The reason why  the loopback-datasource-juggler@2.55.2 was suggested by loopback-team in the first place is due to inconsistency we spotted.  In 5080 everywhere is using loopback-datasource-juggler@2.55.2.  

However,  microgateway does not directly depend on loopback-dataource-juggler, it is an indirect dependencies,  so just by changing the loopback-dataource-juggler version in isolation will not likely to work.  
When microgateway decides to upgrade to newer version, we can work together to figure out at that time.  Thanks all  for investigating.

**Comment by smartmouse** [comment] 2017-08-29 13:05
Notes: For future investigation:
Between loopback-datasource-juggler@2.55.1 and loopback-datasource-jugglrt@2.55.0,
there may be some changes to cause behaviour changes in error-handler, that could be the cause 
why many tests show ERROR since a lots of tests are simulating error cases and expect error messages.

**Comment by jannyHou** [comment] 2017-08-29 15:27
ok we will close it for now, thanks for clarification.

**Closed by jannyHou** 2017-08-29 15:27 UTC
Labels: 5080, team-apex, triaging
