### ISSUE TITLE
Concurrency-induced data loss with embedded models

### ISSUE THREAD

**Issue by sebastianhaas** [strongloop/loopback-datasource-juggler#1173] opened 2016-11-28 23:47 UTC
I just found that posting to an `embedsMany` relation might result in a loss of data if requests are sent with little time in between.

I set up a [test environment to demonstrate this](https://github.com/sebastianhaas/loopback-sandbox/tree/embedsMany) based on `loopback-sandbox`.

### Setup
```json
{
  "name": "Newspaper",
  "plural": "Newspapers",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "articles": {
      "type": "embedsMany",
      "model": "Article"
    }
  },
  "acls": [],
  "methods": {}
}
```
```javascript
{
  "name": "Article",
  "plural": "Articles",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
```javascript
  "Newspaper": {
    "dataSource": "mongodb",
    "public": true
  },
  "Article": {
    "dataSource": "transient",
    "public": false
  }
```
### Steps to reproduce
(For an automated demo see [my test scenario](https://github.com/sebastianhaas/loopback-sandbox/tree/embedsMany).)
1. Start server
2. Post a `Newspaper` instance (`localhost:3000/api/newspapers`)
3. Add an `Article` to that `Newspaper` instance. (`localhost:3000/api/newspapers/id/articles`)

Now everything seems fine, but if you start to repeat 3. with little or no time in between, suddenly `Article`s will be lost. What's worst, you'll still get a `200` response with the correct `Article` bodies, even with ids generated properly so there is no way to tell. I feel horrible about this.

It is probably related to https://github.com/strongloop/loopback-datasource-juggler/issues/677, although I feel like there must be a way to safely add multiple instances to an embedded model. I mean, how am I supposed to handle this application-wise as suggested in #677? What if requests come from different clients at the same time? Also, since its not possible to post an array, what is the suggested time to wait before adding the next object?

**Comment by sebastianhaas** [comment] 2016-11-29 11:25
I was actually able to narrow this done a bit while writing a unit test that covers this scenario- the `memory` connector seems to work fine.

**Comment by sebastianhaas** [comment] 2016-11-29 12:53
A test that would cover this scenario could probably look something like

```javascript
  describe('embedsMany - concurrency', function() {

    var responseAddresses = [];
    var streets = [
      'Street One',
      'Street Two',
      'Street Three',
      'Street Four',
    ];

    before(function(done) {
      db = getMemoryDataSource();
      Person = db.define('Person', {name: String});
      Address = db.define('Address', {street: String});
      Address.validatesPresenceOf('street');

      db.automigrate(['Person', 'Address'], done);
    });

    it('can be declared', function(done) {
      // to save related model itself, set
      // persistent: true
      Person.embedsMany(Address, {
        scope: {order: 'street'},
        options: {persistent: true},
      });
      db.automigrate(['Person', 'Address'], done);
    });

    it('should create embedded items on scope', function(done) {
      Person.create({name: 'Anna'}, function(err, p) {
        should.not.exist(err);
        async.map(streets, function(item, callback) {
          p.addressList.create({street: item}, function(err, address) {
            should.not.exist(err);
            responseAddresses.push(address);
            should.exist(address.id);
            streets.should.containEql(address.street);
            callback(null, address);
          });
        }, function(err, results) {
          should.not.exist(err);
          results.should.have.length(streets.length);
          done();
        });
      });
    });

    it('should return embedded items from scope', function(done) {
      Person.findOne(function(err, p) {
        should.not.exist(err);
        p.addressList(function(err, addresses) {
          should.not.exist(err);

          addresses.should.have.length(streets.length);
          for (var i = 0; i < addresses.length; i++) {
            streets.should.containEql(addresses[i].street);
          }
          done();
        });
      });
    });

  });
```

Note that this will work using the memory connector, but not with (at least) mongo or postgres.

**Comment by jannyHou** [comment] 2017-03-20 21:17
@sebastianhaas Thank you for the repo, I still could not reproduce the problem but seems it's the same issue filed in https://github.com/strongloop/loopback-datasource-juggler/issues/737

I am closing this issue as a dup to keep git clean, let's discuss under the earlier issue. Thanks for understanding.

**Closed by jannyHou** 2017-03-20 21:17 UTC
Labels: #triaging, triage
