### ISSUE TITLE
Model define with scope: {include:['foo','bar']} causes find/findOne to fail if query has includes

### ISSUE THREAD

**Issue by geoffcorey** [strongloop/loopback-datasource-juggler#551] opened 2015-03-30 18:58 UTC
Looks like there is a bug loopback-datasource-juggler/blob/master/lib/utils.js line 86. If I have a default scope for model snafu - scope: { include:['foo','bar'] } and then call find with any query with include: 'snafu' then the resulting merge query would look like include: { 'foo,bar': 'snafu'} which is not correct.

**Comment by geoffcorey** [comment] 2015-03-30 19:21
Quick test in explorer shows that the correct result would be an array as a result of the merge.

include: ['foo','bar','snafu']

**Comment by Terekhov** [comment] 2015-03-30 19:43
If an include from the scope in model.json collides with one from the current context, the JSON's include should probably be ignored.

**Comment by geoffcorey** [comment] 2016-01-27 19:03
Not sure I agree with that.   The idea of a default scope to me means this should be included always.  If you are just overriding the default scope then there really shouldn't have a default scope.

**Comment by clounie** [comment] 2016-01-27 19:38
i.e. default scope +  additive changes only, or you're just designing your default incorrectly, is that what you're saying? That'd seem reasonable.

**Comment by jannyHou** [comment] 2016-05-07 00:00
@geoffcorey do you still run into this issue?
I created an app but fail to reproduce your problem:
link https://github.com/jannyHou/loopback-sandbox/tree/test/scope-include

So if you run the app, create an instance of model `parent`, then create instances of `childone` and `childtwo` belongs to that parent, the result shows well:

```json
[
  {
    "id": 1,
    "childones": [
      {
        "id": 1,
        "parentId": 1
      }
    ],
    "childtwos": [
      {
        "id": 1,
        "parentId": 1
      }
    ]
  }
]
```

**Comment by jannyHou** [comment] 2016-05-20 19:50
I am closing it since it's not reproducible, maybe the bug is fixed already. If anyone able to reproduce it, Please fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace with your code, and feel free to reopen it!
Appreciate your suggestions and help.

**Closed by jannyHou** 2016-05-20 19:50 UTC
Labels: triage, waiting
