### ISSUE TITLE
Impossible to query for existance of a date field

### ISSUE THREAD

**Issue by jirikupiainen** [strongloop/loopback-datasource-juggler#531] opened 2015-03-23 23:11 UTC
find({ where: { dateField: { exists: false }}});

Results in an error, since it tries to make a new Date object from { exists: false }.

Temporary workaround for my use case is not to define the field in the model definition.

**Comment by raymondfeng** [comment] 2015-03-23 23:42
Duplicate of https://github.com/strongloop/loopback/issues/1009

**Closed by raymondfeng** 2015-03-23 23:42 UTC
