### ISSUE TITLE
Attribute as "type:string; required:false;" gives error when is empty

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback-datasource-juggler#627] opened 2015-06-12 07:05 UTC
We have found out, that the empty value for not required fields (string, number etc) gives strange "is blank" errors. For example:

```
"minOrderQuantity": {
    "type": "string",
    "maxLength": 50
},
```

And get error:

```
Details: `minOrderQuantity` is blank (value: "").
```

@raymondfeng  @bajtos is this known feature?

**Comment by bajtos** [comment] 2015-06-19 16:23
I am afraid I cannot reproduce the problem myself. Here is an example code that works for me:

```js
var loopback = require('loopback');
var app = loopback();

var Car = loopback.createModel('Car',
  {
    name: { type: 'string', maxLength: 50 }
  }
);

app.dataSource('db', { connector: 'memory', });
app.model(Car, { dataSource: 'db' });

Car.create(
  { name: '' },
  function(err, created) {
    if (err) throw err;
    console.log('created', created);
  });

// Output:
// created { name: '', id: 1 }
```

@kuskov how can I reproduce the issue on my machine?

**Comment by 0candy** [comment] 2016-06-20 15:21
@ekussberg Has your issue been resolved? Can we close this issue?

**Comment by loay** [comment] 2017-03-15 21:29
Closing issue for now. If you are still experiencing the same problem, please feel free to leave a comment and I will re-open. Also, please review Bajtos's [comment] (https://github.com/strongloop/loopback-datasource-juggler/issues/627#issuecomment-113563762  )above and/or provide a sample repo with steps to reproduce. Thanks.

**Closed by loay** 2017-03-15 21:29 UTC
Labels: juggler-validation, triage, waiting
