### ISSUE TITLE
No actual feedback for delete(All)

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#294] opened 2014-09-06 16:04 UTC
AFAIK none of the delete/destroy methods provide useful feedback whether the delete was completed, and if so, what it affected (in case of deleteAll/where). If nothing matched, there's no way to tell. Taking this further, should this return an error in the case of removeById?

**Comment by raymondfeng** [comment] 2015-02-05 22:34
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/pull/321

**Closed by raymondfeng** 2015-02-05 22:34 UTC
