### ISSUE TITLE
dao.js stripping query keys with undefined values

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-datasource-juggler#373] opened 2014-12-12 15:00 UTC
We discovered a surprising bug in our project today produced by a piece of code like the following,

```
var someObj = { someField: 123 };
MyModel.findOne({where: { someField: someObj.potato }}, ...);
```
Despite ``someObj.potato`` being undefined, ``findOne()`` dutifully returns records from the database (with defined values of ``someField``). It is as if the condition were not included. This circumstance came about when the specification of ``someObj`` changed to include a different property name and this block of code was overlooked. 

I dug into the code and found that within dao.js's ``_normalize``  sits a call to ``utils.removeUndefined``, which strips all undefined keys out of our where condition object.

**Is this by design?** It seems like something prone to produce silent security catastrophes.

**Comment by raymondfeng** [comment] 2015-02-05 21:49
Duplicate of https://github.com/strongloop/loopback/issues/637

**Closed by raymondfeng** 2015-02-05 21:49 UTC
