### ISSUE TITLE
Modify second level related model by the api

### ISSUE THREAD

**Issue by jdrouet** [strongloop/loopback-datasource-juggler#635] opened 2015-06-17 22:12 UTC
Hi everyone,

I actually have these models

Account (exposed through the api) that hasMany Profile
Profile (not exposed) that hasMany Computer
and Computer (not exposed)

I actually use the Account api to add a profile to an account because only the current user can add/modify his own profile (I use an ACL).
How can I add/modify a computer to a profile through the Account api ?

Thank you

**Comment by 0candy** [comment] 2016-05-16 22:09
Can you fork the loopback-sandbox [https://github.com/strongloop/loopback-sandbox] with a sample repo for me to reproduce the issues?
Thanks.

**Comment by jannyHou** [comment] 2016-08-05 21:47
@jdrouet any update about this issue? Are you going to use api in a script or from endpoint?
If from endpoint, this doc about nestRemoting could be helpful:
https://docs.strongloop.com/display/public/LB/Nested+queries
But since you don't expose Profile and Computer you probably could not use nestRemoting in this case.

But you can define a custom remote method(see [doc](https://docs.strongloop.com/display/public/LB/Remote+methods)) and modify ComputerInstance in your custom method.

Since this issue is too old(sorry didn't reply in time), i am closing it here, but  @jdrouet please feel free to reopen it if you still run into problems! Thanks for understanding.

**Closed by jannyHou** 2016-08-05 21:47 UTC
Labels: juggler-relations, triage, waiting
