### ISSUE TITLE
ReferenceError: Cannot create data source "shop": Cannot initialize connector "mysql": time is not defined

### ISSUE THREAD

**Issue by MAHOSSAN** [strongloop/loopback-datasource-juggler#1764] opened 2019-07-29 23:52 UTC
Hello 
I am new to Loopback . I am trying to CRUD operations with web applications . But when i run the applications , it is falling to create datasource named shop . I  have existing tables in mysql database . When i run the server , I am getting following errors in command prompt  .

[ **********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.5
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Users\Khundokar Nirjor\Desktop\loop\cart> node .
C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:280
    throw err;
    ^

ReferenceError: Cannot create data source "shop": Cannot initialize connector "mysql": time is not defined
    at Handshake.Sequence (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\sequences\Sequence.js:28:3)
    at new Handshake (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\sequences\Handshake.js:10:12)
    at Protocol.handshake (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\protocol\Protocol.js:51:32)
    at PoolConnection.connect (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\Connection.js:119:18)
    at Pool.getConnection (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\mysql\lib\Pool.js:48:16)
    at MySQL.connect (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-connector-mysql\lib\mysql.js:90:17)
    at Object.initializeDataSource [as initialize] (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-connector-mysql\lib\mysql.js:44:28)
    at DataSource.setup (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-datasource-juggler\lib\datasource.js:493:19)
    at new DataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-datasource-juggler\lib\datasource.js:138:8)
    at Registry.createDataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\registry.js:364:12)
    at dataSourcesFromConfig (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:570:19)
    at Function.app.dataSource (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback\lib\application.js:269:14)
    at C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:191:9
    at C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:282:5
    at Array.forEach (<anonymous>)
    at forEachKeyedObject (C:\Users\Khundokar Nirjor\Desktop\loop\cart\node_modules\loopback-boot\lib\executor.js:281:20)](url)

here is my datasource.json file
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "shop": {
    "host": "localhost",
    "port": 8081,
    "url": "",
    "database": "shoppingdatabase",
    "password": "",
    "name": "shop",
    "user": "root",
    "connector": "mysql",
    "connectTimeout": 1000000
  }
}

**Comment by dhmlau** [comment] 2019-07-30 17:27
Closing as duplicate of #1765

**Closed** 2019-08-09 01:13 UTC
