### ISSUE TITLE
autoupdate should not be destructive by default

### ISSUE THREAD

**Issue by gregdingle** [strongloop/loopback-datasource-juggler#1294] opened 2017-03-30 22:59 UTC
It's crazy that datasource automigrate will drop columns without even a log warning. Django won't do destructive schema changes by default. That seems sensible. There can always be an override.

**Comment by ssh24** [comment] 2017-04-04 17:03
@gregdingle What is the issue here? 

- `autoMigrate` will drop existing tables (if exists) and rebuild the table with new schema/data or create the table from the scratch if the table does not exist. 
- `autoUpdate` will update the existing table with the new schema/data or create the table from the scratch if the table does not exist.

Use `autoUpdate` instead if you wish to keep your data persistent.

Read more about it on the [docs](https://loopback.io/doc/en/lb2/Creating-a-database-schema-from-models.html)

**Comment by timlind** [comment] 2017-04-04 18:13
@ssh24 the issue is that autoUpdate is destructive, it drops columns. Please change the issue title to autoUpdate

**Comment by ssh24** [comment] 2017-04-04 18:22
That is not correct. Auto-update will not drop columns until and unless the model definition was changed to do so (which is totally up to the end-user to deal with).

**Comment by gregdingle** [comment] 2017-04-04 19:02
@ssh24 sorry for the confusion. I meant `autoupdate` as @timlind said. 

> Auto-update will not drop columns until and unless the model definition was changed to do so (which is totally up to the end-user to deal with).

The problem here is the end user making a mistake. Imagine if there a line in the model deleted accidentally, if there is a typo, if there are multiple versions of an app sharing a database (very common I imagine). 

Also imagine the common scenario for a production app where data needs to be migrated, for example split a column into two. Obviously this must be done manually in the DB but it would be nice afterwards to run automigrate and be told if the updated schema would result in a destructive change, meaning something is still out of sync in the model. 

What happens if the type of a column is changed in the model? Is the column dropped and re-created or is it changed in place with the data intact? I don't know, so I need to back up my table before trying.

**Comment by ssh24** [comment] 2017-04-05 16:17
@gregdingle For any of the above scenario use `autoUpdate` instead of `autoMigrate`. Autoupdate will keep your data intact, whereas automigrate will destroy previous data.

### Straight from the [docs](https://loopback.io/doc/en/lb2/Creating-a-database-schema-from-models.html):
> If there are existing tables in a database, running autoMigrate() will drop and re-create the tables: Therefore, data will be lost. To avoid this problem use auto-update(). Instead of dropping tables and recreating them, autoupdate() calculates the difference between the LoopBack model and the database table definition and alters the table accordingly. This way, the column data will be kept as long as the property is not deleted from the model.

For example, take this scenario into account. I have a table definition (possibly with some data) and I discover that table definition using loopback. Then I could modify the model property types and use autoupdate to change the table definition in the table. Result? My table definition has changed however my data exists.

### Example code (using mysql database and loopback):
#### schema.sql
```
-- create a table and insert some data
create table test (id int not null, name varchar(20), age varchar(20) not null);
insert into test values (1, 'Sakib', '22');
insert into test values (2, 'Sakib', '22');
```
#### bin/script.js
```
'use strict';
var loopback = require('loopback');
var ds = loopback.createDataSource('mysql', {
  'host': 'localhost',
  'port': 3306,
  'database': 'sample',
  'username': '<my_user>',
  'password': '<my_pass>',
});

// Create a model definition by discovering the given table
ds.discoverSchema('test', function(err, model) {
  if (err) throw err;
  // make a new object from the table instance
  var discoveredTable = JSON.parse(JSON.stringify(model));

  // change the object properties
  discoveredTable.properties.age.type = 'Number';
  discoveredTable.properties.age.mysql.dataType = 'int';
  
  // create and attach the model instance to the datasource
  ds.createModel(discoveredTable.name, discoveredTable.properties, discoveredTable.options);

  // autoupdate the model back
  ds.autoupdate(discoveredTable.name, function(err, result) {
    ds.discoverModelProperties('Test', function(err, props) {
      // print out the model properties
      console.log(props);
    });
  });
});
```

Here are the table schema result `before` and `after` running the loopback script:
- **Before**:
```
mysql> show columns from test;
+-------+-------------+------+-----+---------+-------+
| Field | Type        | Null | Key | Default | Extra |
+-------+-------------+------+-----+---------+-------+
| id    | int(11)     | NO   |     | NULL    |       |
| name  | varchar(20) | YES  |     | NULL    |       |
| age   | varchar(20) | NO   |     | NULL    |       |
+-------+-------------+------+-----+---------+-------+
3 rows in set (0.02 sec)

mysql> select * from test;
+----+-------+-----+
| id | name  | age |
+----+-------+-----+
|  1 | sakib | 22  |
|  2 | sakib | 22  |
+----+-------+-----+
2 rows in set (0.00 sec)
```
- **After**:
```
mysql> show columns from test;
+-------+-------------+------+-----+---------+-------+
| Field | Type        | Null | Key | Default | Extra |
+-------+-------------+------+-----+---------+-------+
| id    | int(11)     | NO   |     | NULL    |       |
| name  | varchar(20) | YES  |     | NULL    |       |
| age   | int(20)     | NO   |     | NULL    |       |
+-------+-------------+------+-----+---------+-------+
3 rows in set (0.01 sec)

mysql> select * from test;
+----+-------+-----+
| id | name  | age |
+----+-------+-----+
|  1 | sakib | 22  |
|  2 | sakib | 22  |
+----+-------+-----+
2 rows in set (0.00 sec)
```

Please feel free to close this issue if your question has been answered.

**Comment by gregdingle** [comment] 2017-04-11 01:03
> the column data will be kept as long as the property is not deleted from the model.

I think the data should be kept by default even if the property is deleted from the model. The cost of keeping a deprecated DB column is low, and cost of an accidental deletion is high.

**Comment by ssh24** [comment] 2017-04-11 01:45
Unfortunately, that is how a column from a table is kept synced with its corresponding loopback model property. The loopback model itself is a mirror representation of the table, and any changes to the model is taken into affect upon migration of that model to the database.

We understand your frustration, but this how LoopBack works and the expected behaviour of using `automigrate` is well documented in our [docs](https://loopback.io/doc/en/lb2/Creating-a-database-schema-from-models.html). Upto the end-user if they want to keep the data persistent or not and use the related function (i.e `automigrate` vs `autoupdate`) for it.

**Comment by ssh24** [comment] 2017-04-17 20:29
Closing this as it is not a bug.

**Closed by ssh24** 2017-04-17 20:29 UTC
Labels: apex, triaging

**Comment by baptistdev** [comment] 2019-11-22 16:34
This is still destructive. Removing a property in a model.json drops the column along with data. This renders it useless for production. The argument proposed is that by design the model and schema are kept in sync with the model.json being the dominant config for keeping them in sync. However the destructive nature is dangerous and should not be the default.
