### ISSUE TITLE
Using model.create([]) with Promise.all() results in TypeError: this.getDataSource is not a function

### ISSUE THREAD

**Issue by pantaluna** [strongloop/loopback-datasource-juggler#936] opened 2016-05-19 07:54 UTC
##I want to add a batch of rows to a model using (Bluebird) promises.

I found this pattern at https://github.com/strongloop/loopback/issues/2164#issuecomment-215645590 for using Promise.all() in combination with model.create([]):
```
Promise.all(jobsP.map(Job.create)).then(jobs => {
  console.log('num jobs' + jobs.length);
});
```

I applied that pattern in the project as follows:
```
    Promise.all(inputDataSet.map(cl.create))
      .then(results => {
        console.info('num results:' + results.length);
        console.info('results (array of nulls):');
        console.info(results);
        resolve(results);
      })
      .catch(function (err) {
        console.error('ERROR Promise.all cli.create() FAILED.');
        reject(err);
      });

```

##But the following error comes back consistently at the line <Promise.all(inputDataSet.map(cl.create))>:
```
TypeError: this.getDataSource is not a function at DataAccessObject.create...
```

##console log:
```
addData() The main .catch() TypeError: this.getDataSource is not a function 
at DataAccessObject.create (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\node_modules\loopback-datasource-juggler\lib\dao.js:206:48) 
at Array.map (native) at C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\bin\01-add-data-using-promises.js:39:30 
at Promise._execute (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\node_modules\bluebird\js\release\debuggability.js:272:9) at Promise._resolveFromExecutor (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\node_modules\bluebird\js\release\promise.js:473:18) at new Promise (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\node_modules\bluebird\js\release\promise.js:77:14) at addData (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\bin\01-add-data-using-promises.js:29:10) at Object. (C:\myhtdocs\my-loopback\loopback-sandbox-this-getdatasource\bin\01-add-data-using-promises.js:15:15) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:456:32) at tryModuleLoad (module.js:415:12) at Function.Module._load (module.js:407:3) at Function.Module.runMain (module.js:575:10) at startup (node.js:160:18) at node.js:445:3
```

##Steps To Reproduce:
```
cd ~
git clone https://github.com/pantaluna/loopback-sandbox-this-getdatasource.git
cd loopback-sandbox-this-getdatasource
npm install
node "./bin/01-reproduce.js"
```

Thanks for your help.

**Comment by pantaluna** [comment] 2016-05-19 07:57
Maybe it should be moved to repo strongloop/loopback? But I cannot do that (no auth).

**Comment by jannyHou** [comment] 2016-05-20 03:48
@pantaluna That's fine let's keep you issue here since it's related to build-in  method `create`.
Could you fork https://github.com/strongloop/loopback-sandbox and replace with your code? That would be much easier for me to debug. Thanks.
I will take a look as soon as possible and if it's caused by the same issue in https://github.com/strongloop/loopback/issues/2164#issuecomment-215645590 we can keep our discussion under that one.

**Comment by pantaluna** [comment] 2016-05-20 07:35
@jannyHou Thanks for the follow-up.

>Could you fork https://github.com/strongloop/loopback-sandbox and replace with your code? 
> That would be much easier for me to debug.
I already used the loopback-sandbox to report this reproducible case. See https://github.com/pantaluna/loopback-sandbox-this-getdatasource Or do you mean something else?

**Comment by jannyHou** [comment] 2016-05-20 14:26
@pantaluna Looks great! this is what I need. Thanks.

**Comment by jannyHou** [comment] 2016-05-20 19:06
@pantaluna it also doesn't work for the example in  strongloop/loopback#2164 , same error. Thanks for notifying us this.
Let's close this issue and keep discussion under the parent issue to get more feedback from communities.

**Closed by jannyHou** 2016-05-20 19:06 UTC
Labels: triage

**Comment by pantaluna** [comment] 2016-05-20 19:36
OK
