### ISSUE TITLE
Id is not generating for embeded entity

### ISSUE THREAD

**Issue by sharok** [strongloop/loopback-datasource-juggler#925] opened 2016-05-10 01:53 UTC
I use some models from loopback example, but I save all data in mongodb.
This is my `Customer` model:
```
{
  "name": "Customer",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
    "address": {
      "type": "embedsOne",
      "model": "Address",
      "property": "billingAddress",
      "options": {
        "validate": true       
      }
    }  
  },
  "acls": [],
  "methods": {}
}
```
And `Address` model:
```
{
  "name": "Address",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {  
    "street": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "zipCode": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

```

I made the following request in the explorer:
```
{
  "name": "string",
  "age": 0, 
  "billingAddress": {   
    "street": "string",
    "city": "string",
    "state": "string",
    "zipCode": "string"
  }
}
```

This is response:
```
{
  "name": "string",
  "age": 0,
  "id": "57313cfc603b7cc037a5384f",
  "billingAddress": {
    "street": "string",
    "city": "string",
    "state": "string",
    "zipCode": "string"
  }
}
```
As you can see `id` is present for `Customer` but not for `Address`.
I've tried to define `id` property in the model:
```
 "id": {"type": "string", "generated": true, "id": true},
```

but it didn't help. 

PS. I've also tried to connect `Address` entity to transient data source, tried change base class to `Model`, used `forceId: true` but it didn't help.

**Comment by Amir-61** [comment] 2016-05-17 21:09
I guess that's expected; for `embeds` relation the child's `Address` data is stored in the parent model `Customer`; I guess what you are looking for is `hasOne` where the child data (including the `id`) and parent id are stored in child model.

@superkhau Please correct me if I'm wrong...

**Comment by Amir-61** [comment] 2016-06-05 14:53
Closing this issue since it does seem an expected behaviour. Please feel free to open the issue if you see nay other problems.

Thanks!

**Comment by sharok** [comment] 2016-06-05 15:41
Nobody confirmed that it's expected behavior. If I create nested object
then it's okay. But when I use relation Id has to be generated. I think
it's logical way.

**Comment by Amir-61** [comment] 2016-06-05 15:53
Ok I'm re-opening the issue then. @bajtos @superkhau Could you clarify this please?

Thanks!

**Comment by bajtos** [comment] 2016-06-08 14:31
> I guess that's expected; for `embeds` relation the child's `Address` data is stored in the parent model `Customer`; I guess what you are looking for is `hasOne` where the child data (including the `id`) and parent id are stored in child model.

I agree the current behaviour is expected. For `embedsOne` relation, there is at most one embedded model instance and the only way how to access it is via the parent (owning) instance, thus there is no need for an id.

@sharok if you want a unique `id` field for embedded addresses, then you can generate a property that's set to a new UUID by default:

```
 "id": {"type": "string", "defaultFn": "uuid" },
```

**Closed** 2016-06-08 14:31 UTC
Labels: question
