### ISSUE TITLE
Upsert with composite ID

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback-datasource-juggler#478] opened 2015-03-02 16:52 UTC
I try to upsert a document into my DB (using mongodb), using :
```js
Model.upsert({
  deviceId: myDeviceId,
  appId: myAppId
}, function(err, document){
  console.log(err, document);
});
```

In my model configuration:
```js
{
  "name": "DeviceAppRelation",
  "base": "PersistedModel",
  "properties": {
    "deviceId": {
      "type": "string",
      "id": 1,
      "required": true
    },
    "appId": {
      "type": "string",
      "id": 2,
      "required": true
    }
  }
}
```

But the document is always replaced with first ID. It looks like composite ID are not working with upsert.

It seems that I have the same issue with ```create``` method, if first ID is already present, I have a ```duplicate key error```
Anyone can confirm this ?

**Comment by superkhau** [comment] 2015-03-02 18:14
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by bajtos** [comment] 2015-03-26 11:27
Closing as a duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/121.

**Closed by bajtos** 2015-03-26 11:27 UTC
Labels: triage

**Comment by PradnyaBaviskar** [comment] 2015-03-26 12:12
This can be reproduced this using following steps.

 * Define model as 
```
{
  "name": "Inventory",
  "base": "PersistedModel",
  "properties": {
    "productId": {
      "type": "string",
      "id": 1,
      "required": true
    },
    "locationId": {
      "type": "string",
      "id": 2,
      "required": true
    },
    "quantity": {
      "type": "number",
      "required": false
    }
  }
} 
```

 * Create following ```bootscript```, to populate inventory
```
module.exports = function (app) {
    var Inventory = app.models.Inventory;

    app.dataSources.db.automigrate('Inventory', function(err) {
    if (err) throw err;

    var inventory = [
      {productId: 'P1', locationId: 'L1', quantity: 10},
      {productId: 'P2', locationId: 'L2', quantity: 20},
      {productId: 'P3', locationId: 'L3', quantity: 30}
    ];

    var count = inventory.length;

    inventory.forEach(function(item) {
      Inventory.create(item, function(err, instance) {
        if (err)
          return console.log(err);

        console.log('Inventory created:', instance);

        count--;

        if (count === 0)
          console.log('Done');
      });
    });

    Inventory.upsert({
      productId: 'P1',
      locationId: 'L10',
      quantity: 50
    }, function(err, document){
      console.log(err, document);
    });

  });

};
```
 * Run the application using ```slc run```
 * Finally hit the URL - http://localhost:3000/api/Inventories. Since the record, used for upsert does not already exists, the API should list 4 records, but it lists only 3 of them, wherein the record with ```productid``` P1, is updated by the upserted record.
