### ISSUE TITLE
mongodb aggregation

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback-datasource-juggler#1688] opened 2019-02-02 08:07 UTC
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment] 2019-02-06 16:24
@techaks , could you please provide some information on the question / issue that you have? Thanks.

**Comment by dhmlau** [comment] 2019-02-06 16:25
Looks like you've created another issue.  Closing as duplicate of https://github.com/strongloop/loopback-connector-mongodb/issues/494.

**Closed by dhmlau** 2019-02-06 16:25 UTC
