### ISSUE TITLE
HABTM relationship {order: 'value ASC'} not working at all. 

### ISSUE THREAD

**Issue by vespertilian** [strongloop/loopback-datasource-juggler#644] opened 2015-06-24 06:56 UTC
500 Server error with Postgres and wrong order with memory DB. 

Sample app with tests here

https://github.com/vespertilian/loopback_filter_test

Connect db then NPM test. 

I think this directly relates to the count issue I noted on the forums. 
https://groups.google.com/forum/#!topic/loopbackjs/jqmtqaB8k-M

**Comment by alFReD-NSH** [comment] 2015-12-30 20:23
I'm also experiencing the same issue with Postgres. Right, now I have defined HasAndBelongsToMany relationship between a Company model and Person model and I'm doing this:

```
company.persons({ order: 'firstName ASC' });
```

Which will end up doing this:

```
SQL: SELECT "id","personid","companyid" FROM "public"."personcompany" WHERE "companyid"=$1 ORDER BY "firstname" ASC
```

Which fails because there's no firstname on the PersonCompany through table(generated by loopback). I did some search in the code, and found [this](https://github.com/strongloop/loopback-datasource-juggler/blob/v2.44.0/lib/scope.js#L196-L201) which if I remove, my query works fine.

This issue might be related(or even duplicated) of #720 and #166.

**Comment by dh376** [comment] 2016-04-21 20:42
+1

**Comment by loay** [comment] 2016-05-05 20:24
It seems to me that the issue is a duplicate of this case: 
https://github.com/strongloop/loopback-datasource-juggler/issues/166
Which is already reported as a bug.. It should be fixed as soon as possible. Thanks. 
if you feel it is not related, please leave a comment and I will re-open the issue. Thanks.

**Closed by loay** 2016-05-05 20:24 UTC
Labels: triage
