### ISSUE TITLE
Many to many relations not deleted

### ISSUE THREAD

**Issue by iblazevic** [strongloop/loopback-datasource-juggler#758] opened 2015-11-09 13:49 UTC
We had hard time figuring this one out, cause it was initially working and then stopped at one point and certain endpoint. We did found when is it happening and it seems like it might have been done to work that way but I'm not sure we can work around it, so I would like confirmation on is this a bug or is it supposed to work that way.

Problem is many-to-many relations. We are using postgres btw. Also I created a small project with just one many to many relation in there https://github.com/EastCoastProduct/many-to-many-bug to isolate and show on example whats happening.

Example: lets say we have person in few different teams and data looks like this:

    test=# select * from team;
     name  | id 
    -------+----
     team1 |  1
     team2 |  2
     team3 |  3
     team4 |  4
    (4 rows)

    test=# select * from personteam;
     id | personid | teamid 
    ----+----------+--------
      1 |        1 |      1
      2 |        1 |      2
      3 |        1 |      3
      4 |        1 |      4
    (4 rows)

Doing DELETE on /api/people/{id}/teams/{fk} does what it should.

    test=# select * from team;
     name  | id 
    -------+----
     team1 |  1
     team2 |  2
     team3 |  3
    (3 rows)

    test=# select * from personteam;
     id | personid | teamid 
    ----+----------+--------
      1 |        1 |      1
      2 |        1 |      2
      3 |        1 |      3
    (3 rows)

However, doing DELETE on api/teams/3 doesn't delete the relation and leaves database with broken data, cause we have something that should be FK pointing to non existing row and it leaves this state in database:

    test=# select * from team;
     name  | id 
    -------+----
     team1 |  1
     team2 |  2
    (2 rows)

    test=# select * from personteam;
     id | personid | teamid 
    ----+----------+--------
      1 |        1 |      1
      2 |        1 |      2
      3 |        1 |      3
    (3 rows)

You can clearly see in personteam table relation still pointing to deleted team.

Now from what I'm reading it doesn't seem like we are able to set this behaviour on model, we can't set CASCADE nor can we force FKs (true DB FKs) in model definition. Unless we can do that and I was just unable to find it, seems weird that route itself decides what relations get deleted. One option would be having our own custom migrations on top of loopback to enforce FKs and proper cascading. But I really don't like that we would have to manage both loopback models and own custom migrations.

Is there a way to declare proper cascades and behavior in the models, cause this seems like a big issue at least for our use case.

Also if it was intended to work this way and get from route what needs to be deleted, not sure what would route look like if we had multiple relations to same table?

Thanks.

**Comment by Amir-61** [comment] 2016-06-05 03:23
Hey @iblazevic,

It helps me a lot to triage this ticket if you can please provide me with a sample repo using our [loopback-sandpox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue.

Thanks a lot!

**Comment by iblazevic** [comment] 2016-06-06 10:16
Hi @Amir-61,

I'm glad you are taking a look at this, its been some time since this happened and I did create that repo thats linked up there to illustrate the problem better, if thats not enough I'll try to make it more clear when I get more time.

Thanks

**Comment by Amir-61** [comment] 2016-06-06 19:15
Hey @iblazevic,

I believe this ticket possibly a duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/88

Thanks!

**Comment by Amir-61** [comment] 2016-06-15 15:01
Closing this issue in favour of https://github.com/strongloop/loopback-datasource-juggler/issues/88

Thanks!

**Closed by Amir-61** 2016-06-15 15:01 UTC
Labels: duplicate, question, triage
