### ISSUE TITLE
Related items via hasMany relationship duplicated onto parent model when saved

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-datasource-juggler#754] opened 2015-11-05 00:00 UTC
Got a bit of a serious one here. Essentially, if you load a model instance with some included relationship data, and then call `save()` on the model instance, the data from the child relationships ends up being stored directly on the parent model, and subsequent attempts to load the relationship data retunds duplicated and corrupt data.

I've created a sandbox along with a test case that highlights the issue:

https://github.com/fullcube/loopback-sandbox/tree/relationship-issue

The issue is highlighted and described in this test case:
https://github.com/fullcube/loopback-sandbox/blob/relationship-issue/test/test.js#L51

You can run the test like:

`mocha test/test.js`

```
  it('saving parent only', function(done) {
    app.models.Membership.findById(1, {
      include: 'subscriptions'
    })
      .then(function(membership) {
        var subscriptions = membership.subscriptions();
        console.log('Initially we have the 3 subscriptions from sample data:');
        console.log(subscriptions);
        expect(subscriptions).to.have.length(3);

        // This causes the subscrptions that were fetched from the include
        // elationship to be saved directly onto the membership.
        return membership.save();
      })
      .then(function(updatedMembership) {
        // Now, try to load the membership again, along with its subscriptions.
        return app.models.Membership.findById(1, {
          include: 'subscriptions'
        });
      })
      .then(function(membership) {
        // Now, we actaullly have 5 subscriptions instead of the 3 that
        // we should have. Subscriptions 2 and 3 have duplicates.
        var subscriptions = membership.subscriptions();
        console.log('Now we have 5 subscriptions!');
        console.log(subscriptions);
        expect(subscriptions).to.have.length(3);
      })
      .then(done)
      .catch(done);
  });
```

which outputs:
```
Initially we have the 3 subscriptions from sample data:
[ { id: '1', provider: 'someprovider', membershipId: '1' },
  { id: '2', provider: 'someprovider', membershipId: '1' },
  { id: '3', provider: 'someprovider', membershipId: '1' } ]
Now we have 5 subscriptions!
[ { id: '1', provider: 'someprovider', membershipId: '1' },
  { id: '2', provider: 'someprovider', membershipId: '1' },
  { id: '3', provider: 'someprovider', membershipId: '1' },
  { id: '2', provider: 'someprovider', membershipId: '1' },
  { id: '3', provider: 'someprovider', membershipId: '1' } ]
    1) saving parent only


  1 passing (113ms)
  1 failing

  1) related items saving parent only:
     AssertionError: expected [ Array(5) ] to have a length of 3 but got 5
      at test/test.js:77:39
```

There is some console output that shows the issue. I've also configured the db connector to store the data in a file called `db.json` which you can look at to clearly see the underlaying data issue.

Unless my understanding of what `save()` is supposed to do is completely out the window, I'd really like to see this handled as a high priority as the end result is a highly corrupted database, and relationships that return incorrect data, which when used in the scope of an application can lead to sever application-wide data duplication and corruption.

**Comment by mrfelton** [comment] 2015-11-05 10:46
Some observations:

1. When the individual model instances are first created, they are saved to the correct place. That is to say that the parent item is saved as a single document in the correct collection, and the child items are saved individually as standalone documents in the correct collection.

2. When you call `save()` on a model instance that has relationship data included via the `include` filter, the child instances are embedded onto the parent model and save with the parent in it's collection. The standalone child documents are untouched.

3. If you load the relationship data, change a value of one of the child instances and save the parent, the updated child instance data is saved into the embedded data from the parent document, whilst the standalone child documents are left untouched. So now you have duplicate data with outdated data in the standalone documents and updated data embedded directly onto the parent document.

4. Multiple copies of the same document can become embedded directly into the parent document, all with the same uuid, often with different data.

5. Once data has become embedded directly into the parent document, the standalone child documents are never updated.

6. Once data has become embedded directly into the parent document, relationships fail to function fully. If you get hold of a child instance via the getter method (eg `memberships.subscription()[0]` what you actually get back is simple json and not a model instance with the usual prototype methods attached)

**Comment by Joesimonsen** [comment] 2015-11-05 23:01
Zendesk ticket #1214 has been linked to this issue and is now the primary ticket.

**Comment by raymondfeng** [comment] 2015-11-05 23:52
This is unfortunately the side-effect of schema-less data model. The situation is pretty much like the following:

1. Find a model instance (order) by id from mongodb 
2. add lineitems to the order object
3. Save it back to mongodb.

Now your mongodb has the embedded lineitems.

I'm not sure what's the best way to fix it. The result from a query with include is already polluted. I saw a few options:

1. Add `options.strict` to save so that it persists known properties
2. When `include` is only, the related objects will be stored into a different internal property, such as `__included` to separate from `__data`

**Comment by mrfelton** [comment] 2015-11-06 00:18
> Add options.strict to save so that it persists known properties

Do you envisage this as an option that the caller would have to set explicitly? It would seed to me that as loopback included additional data onto the scope via a relationship it should by default treat it differently from standard document properties and persist it in the save call.

>When include is only, the related objects will be stored into a different internal property, such as __included to separate from __data

Seems sensible. If we don't store the relationship data as if it were a normal property in the first place, then presumably it wouldn't then get handled as one when the instance is persisted.

**Comment by mrfelton** [comment] 2015-11-15 13:30
@raymondfeng In this PR I'm cleaning up the data that's just about to be persisted in `.save()` by using `inst._initProperties()`. This prevents the relationship data from being persisted along with the model data. Interested to hear your feedback with this approach.

**Comment by mrfelton** [comment] 2015-11-17 15:02
Some related historical issues https://github.com/strongloop/loopback/issues/742 https://github.com/strongloop/loopback-datasource-juggler/pull/666

**Comment by mrfelton** [comment] 2016-01-08 10:10
The good news is that issue appears to have been fixed in between and 2.41.2 and 2.42.0. The bad news is that I don't believe there is a test case that proves that is so and therefore I don't have confidence that the issue wont appear again in a later version. I'll add a test case to verify.

**Comment by 0candy** [comment] 2016-05-04 15:00
@mrfelton So this issue is resolved? Can I close the issue?

**Comment by Amir-61** [comment] 2016-07-24 18:20
>The good news is that issue appears to have been fixed in between and 2.41.2 and 2.42.0.

Closing this ticket since the problem is solved

>The bad news is that I don't believe there is a test case that proves that is so and therefore I don't have confidence that the issue wont appear again in a later version. I'll add a test case to verify.

Please send a PR to write the test case and we will review it and land it. Thanks again for contribution :-)

**Closed** 2016-07-24 18:20 UTC
Labels: juggler-relations, triage

**Comment by jdhrivas** [comment] 2017-01-09 19:04
@mrfelton  @Amir-61 
 I'm having this problem using: "loopback-datasource-juggler": "^2.53.1".
I'm performing an updateAll operation passing the original model with some updated properties, but my first query needs to include a related model for some computations like this:

`  Charge.findById(data.id)
      .then(function (charge) {
        return Promise.all([
          Charge.updateAll({id: charge.id}, data), // at this point data includes related model object
          Helper.updateFeeAmount(charge)
        ])
      })
`
I could manually cleanup 'data' but I wanted to check if there is already a fix for this.

**Comment by raghavadss** [comment] 2017-08-02 12:20
Im using 3.0.0 and seeing this issue of embedded properties coming from include getting persisted on calling save()

**Comment by bajtos** [comment] 2017-08-03 09:31
@jdhrivas please open a new issue with full steps how to reproduce the problem. See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
