### ISSUE TITLE
Cannot use *constructor* as an attribute name

### ISSUE THREAD

**Issue by nimaen** [strongloop/loopback-datasource-juggler#762] opened 2015-11-15 15:00 UTC
Hi, 
I wanted to test loopback using a Car model with a constructor attribute.
Fact is, it cannot be validated because of this part of the code in `lib/validations.js`.

```js
if (typeof attr === 'string') {
  var validation = extend({}, conf);
  validation.options = opts || {};
  cls.validations[attr] = cls.validations[attr] || [];
  cls.validations[attr].push(validation);
}
```

Seems pretty logical to me now, but just wanted to tell you just in case; should be part of the documentation.

**Comment by superkhau** [comment] 2015-11-16 04:10
@crandmck ^

**Comment by bajtos** [comment] 2015-11-27 09:21
To be honest, this looks like a bug to me. We should use `Object.create(null)` instead of `{}` to initialise new key-value maps. That will support all different attribute names like `constructor`, `__proto__`, etc.

**Comment by bnoordhuis** [comment] 2015-11-27 11:19
> Do you know of any reasons why it may be a bad idea to support attribute (property) names like `constructor` and `__proto__` in LoopBack models?

`Object.create(null)` is slower than an object literal, like 10-20x slower.  We're talking nanoseconds though.

**Comment by raymondfeng** [comment] 2015-11-27 18:42
Maybe we should blacklist a list of `reserved words` so that they won't be used for property names or provide an `escaping` mechanism.

**Comment by bnoordhuis** [comment] 2015-11-27 22:59
You might as well use `Object.create(null)` or `{ __proto__: null }` in that case.  The performance loss likely gets more than made up by not needing any hairy filtering and transformation steps.

**Comment by piscisaureus** [comment] 2015-11-28 18:35
I agree with @bajtos initial idea of using Object.create(nulll).
@bnoordhuis is right in that the performance impact is probably negligible.

**Comment by crandmck** [comment] 2015-11-30 23:45
For docs, is the restriction that you can't use `constructor` as a model property name?  Can you use it as a model name?  A relation name, etc?  Are there other "reserved words" that you can't use as names?

Here is what we say now: https://docs.strongloop.com/display/LB/Valid+names+in+LoopBack.  It's fairly vague.

**Comment by jannyHou** [comment] 2015-12-02 17:11
I reproduced this issue by adding `constructor` as a property to a model:
```
 "constructor": {
      "type": "string"
    }
```
I use Visual Studio Code as editor and it warns me `Duplicate object key`
And when I run the app I got error from https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L66
`constructor` is not in the ['javascript reserved words'](https://mathiasbynens.be/notes/reserved-keywords) list (mentions here https://docs.strongloop.com/display/public/LB/Valid+names+in+LoopBack), but I think it's one of "predefined names of implementation-dependent JavaScript objects, methods, or properties", and that's why it fails.
More details could be found in this link from javascript faq: http://www.javascripter.net/faq/reserved.htm
I am not sure if that link is an official link, if not, I will try to find out official reference from javascript.
Thanks!

**Comment by bajtos** [comment] 2015-12-08 14:58
Oh, so this issue is more complex than I originally thought.

We are using `instance.constructor` to get hold of the constructor function, as can be seen e.g. [here](https://github.com/strongloop/loopback-datasource-juggler/blob/80c3bd9d419e501d5b7beb0a623c8b1eaefdc258/lib/model.js#L64-L69):

```js
ModelBaseClass.prototype._initProperties = function (data, options) {
  var self = this;
  var ctor = this.constructor;

  if(data instanceof ctor) {
    // Convert the data to be plain object to avoid pollutions
    data = data.toObject(false);
  }
  // etc.
}
```

I don't know of any alternative way how to get hold of object constructor, therefore I agree it's best to add `constructor` to the list of "reserved words" that cannot be used for property names.

We should also implement measures to prevent this from happening:
 - modify juggler's model-builder to throw an error when model definition contains `constructor` property
 - modify `_initProperties` and other functions assigning raw data to model instance to ignore `constructor` fields, preferably with a warning
 - modify `slc loopback:property` and relation generator to refuse to create a property called `constructor`

**Comment by bnoordhuis** [comment] 2015-12-08 15:18
It probably doesn't help much but the idiomatic ES6 version of that check is:
```javascript
if (Object.getPrototypeOf(this).isPrototypeOf(data)) {
  // ...
}
```
No need to reference the `.constructor` property.

**Comment by bajtos** [comment] 2015-12-09 15:08
@bnoordhuis thanks! It looks like this check works on Node 0.10 too.

Why do you think it doesn't help much?

**Comment by bnoordhuis** [comment] 2015-12-09 16:13
For some reason I thought those methods didn't exist in v0.8 and v0.10 but you're right, they do.

**Comment by bajtos** [comment] 2015-12-10 18:50
On the second thought, I think it will be safer to reject `constructor` model properties in LoopBack. While we can fix juggler/remoting/loopback to support it, I fear it is likely the problem will quickly surface again in other parts of user applications, e.g. HTML5 clients. In other words, `constructor` property is a footgun that's better to be avoided as early in the development process as possible.

Let's keep the scope of this GH issue to fix the documentation, and then continue the work in https://github.com/strongloop-internal/scrum-loopback/issues/642 (Add validation to avoid using "constructor" as model property name)

**Comment by crandmck** [comment] 2015-12-14 23:19
Janny added a brief note to https://docs.strongloop.com/display/LB/Valid+names+in+LoopBack (last sentence in the article) and I edited.  AFAIC, we can close this now.  @bajtos please close if that's sufficient for now.

**Comment by jannyHou** [comment] 2016-02-03 18:19
I am closing it since https://github.com/strongloop/loopback-datasource-juggler/pull/823 has been merged.

**Closed by jannyHou** 2016-02-03 18:19 UTC
Labels: beginner-friendly, doc
