### ISSUE TITLE
lost ability to perform a geo search filter[where][loc][near]=

### ISSUE THREAD

**Issue by rptally** [strongloop/loopback-datasource-juggler#1102] opened 2016-09-20 15:18 UTC
A simple query that works correctly in the loopback-datasource-juggler 2.49.0

    https://[server]/api/stores?filter[where][loc][near]=32.816024,-96.770074

has the following error when executed with in loopback-datasource-juggler 2.50.0

    fred-api-dev-0 (err): Error: Callback was already called.
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/async/dist/async.js:844:36
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/async/dist/async.js:3676:17
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/async/dist/async.js:339:31
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:694:7
    fred-api-dev-0 (err):     at execStack (/var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:493:7)
    fred-api-dev-0 (err):     at RemoteObjects.execHooks (/var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:497:10)
    fred-api-dev-0 (err):     at interceptInvocationErrors (/var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:693:10)
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:148:21
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:148:21
    fred-api-dev-0 (err):     at /var/www/fred-api/develop/source/fred-api/node_modules/loopback/node_modules/loopback-phase/node_modules/async/lib/async.js:148:21

Note: The issue exists in the 2.51.0 update as well.

**Comment by Amir-61** [comment] 2016-09-20 19:35
@rptally 
Thanks for bringing this up; it seems this is a regression from a recent work. Could you please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) so I can reproduce it on my local machine and then I can escalate it?

Thanks!

**Comment by Amir-61** [comment] 2016-09-20 20:14
@rptally Are you using `loopback-connector-mongodb`? If so, I suspect this is a regression from a recent community [PR#259](https://github.com/strongloop/loopback-connector-mongodb/pull/259); @superkhau since you are reviewed that PR, you may have a better insight.

**Comment by Amir-61** [comment] 2016-09-20 20:36
Closing in favour of https://github.com/strongloop/loopback-connector-mongodb/issues/285

**Closed by Amir-61** 2016-09-20 20:36 UTC
Labels: triage
