### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined using @2.55.1

### ISSUE THREAD

**Issue by yshing** [strongloop/loopback-datasource-juggler#1434] opened 2017-07-22 20:43 UTC
# Description/Steps to reproduce
Running loopback in docker node-apline 6.11

Working fine with 2.54.1. And throws following error when using 2.55.1.

# Expected result
Should be working without throwing error
```
TypeError: Cannot read property 'properties' of undefined
    at Function.DataAccessObject._coerce (/usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:1615:60)
    at Function.DataAccessObject._normalize (/usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:1511:8)
    at Function.find (/usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:1855:10)
    at prepareForTokenInvalidation (/usr/src/app/node_modules/loopback/common/models/user.js:889:15)
    at notifySingleObserver (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:104:22)
    at iterate (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:181:13)
    at Object.async.eachSeries (/usr/src/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:197:9)
    at doNotify (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:101:11)
    at doNotify (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/usr/src/app/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at /usr/src/app/node_modules/loopback-datasource-juggler/lib/dao.js:2608:11
```

# Additional information

**Comment by a-legrand** [comment] 2017-07-24 10:51
same here

**Comment by glesage** [comment] 2017-07-26 16:32
also seeing this, using 2.55.0 until fixed

**Comment by rmg** [comment] 2017-07-27 14:48
@yshing @a-legrand @glesage do you happen to have model definitions like what are being fixed in strongloop/microgateway-datastore#11?

**Comment by a-legrand** [comment] 2017-07-27 15:10
Nope, none of my models has {} as a property definition

**Comment by rmg** [comment] 2017-07-27 15:16
@a-legrand the problem also shows up for the `[]` properties.

We're trying to track down if the issue there is a separate regression that just happened to be caused by the same PR as this issue or not.

**Comment by a-legrand** [comment] 2017-07-27 15:20
All my properties are defined, with at least a type

**Comment by kjdelisle** [comment] 2017-07-27 20:51
So, after much hacking about and attempting to create tests to break the scenario, the only thing I could come up with was something along these lines:
```
it('explodes in my face :( ', function() {
   // extending the tests in loopback-dl.test.js
    var item = {};
    model.definition.properties['foo'] = {};
    where = model._coerce({'foo.bar': item});
    assert.strictEqual(where['foo.bar'], item);
  });
```

Any of the properties I attempted to define on the model _at creation time_ were correctly handled by the existing code in 2.55.1. It was only when I programmatically altered the model's definition, specifically the properties, that I could even come close to replicating this sort of error.

@yshing @a-legrand @glesage Are any of you modifying the models programmatically in this manner?

**Comment by kjdelisle** [comment] 2017-07-27 20:52
I don't want to say that I'm certain this is the only way to come up with something like this, but I'd like to flesh out my understanding of how you're running into this before I dig further.

**Comment by yshing** [comment] 2017-07-28 15:34
By the doc, lookback support the `Object` type [here](https://loopback.io/doc/en/lb2/LoopBack-types.html)

Basically you defines the type like 
```javascript
{
  "meta": {
    "type": "Object"
  }
}
```

After #1361 ,
When you query sth like
```javascript
Model.find({'meta.foo': 'bar'})
```

It throws that error.

Guess it's because `type.definition.propeties` doesn't exist for Object or ANY type.

The fix is by applying a check before using `type.definition.properties` as suggested by @bajtos.

For the test case please check 2a2589b04b453922f100e40ab49726742185d5d5

Not very sure where to put the test case..

Pull request #1444 should be fine..

**Comment by kjdelisle** [comment] 2017-07-28 15:48
That's odd...my attempt to replicate it was more directly at the `_coerce` function, but I can confirm that your PR's test case does fail without the fix, and succeeds once it's in place.

**Comment by rmg** [comment] 2017-07-28 16:43
@yshing which connector/datasource are you using?

**Comment by kjdelisle** [comment] 2017-07-28 20:35
loopback-datasource-juggler@2.55.2 released, please reply here if the issue persists. Closing.
@a-legrand @glesage

**Closed by kjdelisle** 2017-07-28 20:35 UTC
Labels: bug, critical, in-progress, team-apex
