### ISSUE TITLE
updateOrCreate does not return error in case of "error"

### ISSUE THREAD

**Issue by harshu108** [strongloop/loopback-datasource-juggler#914] opened 2016-04-26 08:52 UTC
When my connector returns error in callback to updateOrCreate, the dao.js doesn't mitigate it back.

  ```
     function done(err, data, info) {
          var context = {
            Model: Model,
            data: data,
            isNewInstance: info && info.isNewInstance,
            hookState: ctx.hookState,
            options: options,
          };
          Model.notifyObserversOf('loaded', context, function(err) {
            if (err) return cb(err);
```

The call returns to `function done()` and it straight away notifies observers. The line that checks for error is missing.

**Comment by Amir-61** [comment] 2016-05-17 21:59
Thanks @harshu108,

Thats an easy fix could you please contribute a patch and please ping me in the PR you send so I'll make sure it gets landed ASAP.

Also please add test case reproducing the issue in our test suite.

Thanks

**Comment by Amir-61** [comment] 2016-06-01 02:19
@harshu108,

On the second thought since it is an obvious bug, we may not need any test case for that. I just sent [a PR](https://github.com/strongloop/loopback-datasource-juggler/issues/914) to fix this.

Thanks for reporting this issue :-)

**Comment by Amir-61** [comment] 2016-06-01 02:19
Connect to https://github.com/strongloop/loopback-datasource-juggler/issues/914

**Comment by Amir-61** [comment] 2016-06-02 12:39
Landed https://github.com/strongloop/loopback-datasource-juggler/pull/954. 

Closing the ticket now!

Thanks for reporting the error!

**Closed by Amir-61** 2016-06-02 12:39 UTC
Labels: #wip, beginner-friendly, bug, triage
