### ISSUE TITLE
removeUndefined in doDelete() will cause destroyAll items in table.

### ISSUE THREAD

**Issue by TonnyTao** [strongloop/loopback-datasource-juggler#479] opened 2015-03-04 08:03 UTC
This is a great disaster!

```javascript
Tag.destroyAll({userId: undefined})   //this will remove all tags in Tag table.
```

**Comment by raymondfeng** [comment] 2015-03-04 18:16
Should we report it as an error if `undefined` values are seen in the `where` statement?

**Comment by fabien** [comment] 2015-03-06 20:47
Yes, we should throw in this case. Unlike `null`, `undefined` is really tricky.

**Comment by raymondfeng** [comment] 2015-03-06 20:48
PR is welcome!

**Comment by loay** [comment] 2016-01-14 21:23
Hi @TonnyTao 
The issue is reported as a bug: https://github.com/strongloop/loopback-datasource-juggler/issues/492
We will try to fix it as soon as we can. 
Thanks.

**Comment by loay** [comment] 2016-01-15 19:31
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/492

**Closed by loay** 2016-01-15 19:31 UTC
Labels: duplicate, triage
